### ISSUE TITLE
Every time I upload a screenshot with "Copy URL after Upload" enabled I can't do anything on my desktop until it's uploade

### ISSUE THREAD

**Issue by ghost** [33kk/flameshot#1]
**Flameshot version**
r561.914e27e-1

**Describe the bug**
like in title (don't know if it would happen in normal flameshot).

**To Reproduce**
I upload a screenshot and I can't do anything on my desktop like opening shortcuts and stuff like that..

**Expected behavior**
That it just normally uploads and being copied

**System Information**
Manjaro kde with kernel version 5.9.3-1

**Comment by 33KK** [comment]
I don't think that this is issue of my fork. Does it happen with Imgur uploader?

Haven't noticed any problems on Arch with bspwm, maybe it's KDE specific.

**Comment by ghost** [comment]
It was an issue of the original program and it's fixed with the newest version.
