### ISSUE TITLE
[Question] Is it possible to shorten the custom upload with an ip grabber and bit.ly?

### ISSUE THREAD

**Issue by ghost** [33kk/flameshot#2]
I want that if I upload an image to for example [i.nuuls.com/upload](https://i.nuuls.com/upload) that then it gets shortened by an ip grabber like [iplogger.org](https://iplogger.org/) and then shortened by [bit.ly](https://bitly.com/) or any other link shortener so that the people who click on it won't find it out.
That would be handy cause I send many ip grabber links cause I just need to know if there is one idiot who uses internet explorer or edge.

**Comment by 33KK** [comment]
Yeah yeah, sure, you need. I'm not going to help you with that.
